name: Bug report
description: Create a report to help me improve the [Re]Structure plugin
labels: bug
body:
 - type: checkboxes
   attributes:
    label: Issue tracker rule checks (please read carefully)
    options:
     - label: "I have checked that my problem <a href='https://github.com/Gregory-AM/ReStructure-Plugin/issues' target='_blank'>is not already reported</a>"
       required: true
     - label: "I have checked that my problem is not already fixed"
       required: true
 - type: textarea
   attributes:
    label: Issue description
    description: Explain clearly and unambiguously what went wrong
    placeholder: |
      Tell us here about the bug/problem
   validations:
    required: true
 - type: dropdown
   attributes:
    label: [Re]Structure Version
    description: Which Plugin Version were you using?
    options:
     - v1.0.0
     - v1.1.0
     - v1.2.0
   validations:
    required: true
 - type: textarea
   attributes:
    label: How to reproduce this issue?
    description: Try to explain what you did for the bug to occur. Try to share screenshots
    placeholder: |
      Step 1: ...
      Step 2: ...
      ...
   validations:
     required: true
 - type: dropdown
   attributes:
    label: Operating system
    description: Which operating system do you use?
    options:
     - Windows
     - Linux
     - Other (Specify in the next section)
   validations:
     required: true
 - type: textarea
   attributes:
    label: Additional System Details
    description: Provide information about your setup and system
    placeholder: |
      Version: [v1.2 / v2.1 ...]
   validations:
     required: true
 - type: textarea
   attributes:
    label: Logs (if applicable)
    description: Include any relevant logs if possible
    placeholder: |
      [example_log.txt / example_log.md ...]
   validations:
    required: false
