name: Discord Release Notification

on:
  release:
    types:
      - release
  workflow_dispatch:

jobs:
  send_discord_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord Message
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RELEASE_NAME: ${{ github.event.inputs.tag }}
          RELEASE_URL: 'manual trigger'
          RELEASE_CREATED_AT: 'manual trigger'
        run: |
          PAYLOAD=$(cat <<-EOF
          {
            "content": null,
            "embeds": [
              {
                "title": "${RELEASE_NAME}",
                "url": "${RELEASE_URL}",
                "color": 8435015,
                "footer": {
                  "text": "Released"
                },
                "timestamp": "${RELEASE_CREATED_AT}"
              }
            ],
            "attachments": []
          }
          EOF
          )
          
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
